# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://wtlucky.github.com/geekerprobe
title: GeekerProbe
subtitle: 水滴石穿 Keeping faith.
author: wtlucky <chinawtlucky@gmail.com>
simple_search: http://google.com/search
description:

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /geekerprobe/atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /geekerprobe
permalink: /blog/:year/:month/:day/:title/
source: source
destination: public/geekerprobe
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [custom/asides/category_list.html, custom/asides/ds_recent_comments.html, asides/recent_posts.html, custom/asides/weibo.html, asides/twitter.html,  asides/github.html, asides/googleplus.html, custom/asides/tags.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
blog_index_asides: [custom/asides/about.html, custom/asides/category_list.html, asides/recent_posts.html, custom/asides/weibo.html, asides/twitter.html,  asides/github.html, asides/googleplus.html, custom/asides/tags.html]
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: wtlucky
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: cz_wtlucky
twitter_tweet_count: 2
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true

# Weibo  
# Please refer to http://weibo.com/tool/weiboshow to get your uid and verifier.   
weibo_uid: 2381129390       # 填入uid  
weibo_verifier: 4d52a72a   # 填入verifier  
weibo_fansline: 0      # 粉丝显示多少行  
weibo_show: false      # 是否显示最近微博内容  
weibo_pic: true          # 是否显示微博中的图片  
weibo_skin: 1          # 使用哪种配色风格，数字为从1开始的微博秀风格序号  
weibo_share: false     # post文章后是否显示分享到

# Google +1
google_plus_one: true
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: chinawtlucky@gmail.com
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name:
disqus_show_comment_count: false

# Duoshuo Comments
duoshuo_comments: true
duoshuo_short_name: shuidishichuan
duoshuo_asides_num: 5       # 侧边栏评论显示条目数
duoshuo_asides_avatars: 0   # 侧边栏评论是否显示头像
duoshuo_asides_time: 0      # 侧边栏评论是否显示时间
duoshuo_asides_title: 0     # 侧边栏评论是否显示标题
duoshuo_asides_admin: 0     # 侧边栏评论是否显示作者评论
duoshuo_asides_length: 18   # 侧边栏评论截取的长度

# Google Analytics
google_analytics_tracking_id: UA-38777768-1

# Facebook Like
facebook_like: true

# bShare
# 集合分享平台
bShare_enable: true

# tag-cloud
tag_dir: tags
